import Background from "../public/man3.png";

export const carouselsArray = [
    {
        title: " Decorative Coasters Made With Artificial Intelligence",
        subTitle: "A Collection Of Art - Ceated By Artists Around The World - Generated By",
        para: "Al - Printed On High Quality Coasters.",
        image: Background
    },
    {
        title: " Decorative Coasters Made With Artificial Intelligence",
        subTitle: "A Collection Of Art - Ceated By Artists Around The World - Generated By",
        para: "Al - Printed On High Quality Coasters.",
        image: Background
    },
    {
        title: " Decorative Coasters Made With Artificial Intelligence",
        subTitle: "A Collection Of Art - Ceated By Artists Around The World - Generated By",
        para: "Al - Printed On High Quality Coasters.",
        image: Background
    },
    {
        title: " Decorative Coasters Made With Artificial Intelligence",
        subTitle: "A Collection Of Art - Ceated By Artists Around The World - Generated By",
        para: "Al - Printed On High Quality Coasters.",
        image: Background
    }
]